# Site settings
title: Alberto Russo
description: 'Sono un <strong>Full stack developer</strong> e mi occupo dello sviluppo di <strong>applicazioni web</strong> e <strong>mobile</strong> prevalentemente in <strong>Symfony</strong>, <strong>Angular/Nodejs</strong> e <strong>Ionic</strong>.'
url: 'http://albertorusso.it'
baseurl: ''
google_analytics: 'UA-35241392-1'
disqus_shortname: 'albertorusso'

# Google webmaster tools
google_verify: sCYYda-4oc8Oopy5au8WHLPZMzj4Phtwtv8ksgCFzBY

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 1C5318424199AD200C1EB9F07BF37C01

# Alexa web analytics toolkit http://www.alexa.com/
alexa_verify: ORqyzruaqLKGAY2AIYGbm4ZaPhI

author:
  name: 'Alberto Russo'
  email: me@albertorusso.it
  twitter_username: albertorusso
  facebook_username: russo.alberto
  github_username:  russoalberto
  linkedin_username:  russoalberto

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 2
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
